[project]
name = 'Decentralized-Medical-Equipment-Donation-Tracking'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.donor-verification]
path = 'contracts/donor-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.equipment-certification]
path = 'contracts/equipment-certification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
